import os
import threading
from http.server import HTTPServer, BaseHTTPRequestHandler
import edge_tts
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, MessageHandler, CallbackQueryHandler, ContextTypes, filters

BOT_TOKEN = "8942545300:AAFoQnlKoC4A982dIpTGrXfWgaBw9UsKviU".strip()

user_voices = {}

VOICES = {
    "female": "bn-BD-NabanitaNeural",
    "male_bd": "bn-BD-PradeepNeural"
}

# Render Server Port Handling
class HealthServer(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b"Bot is running!")

def run_health_server():
    port = int(os.environ.get("PORT", 8080))
    server = HTTPServer(("0.0.0.0", port), HealthServer)
    server.serve_forever()

threading.Thread(target=run_health_server, daemon=True).start()

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    keyboard = [[
        InlineKeyboardButton("👨 পুরুষ কণ্ঠ (Pradeep)", callback_data='male_bd'),
        InlineKeyboardButton("👩 নারী কণ্ঠ (Nabanita)", callback_data='female')
    ]]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await update.message.reply_text(
        "স্বাগতম! আমি আপনার প্রফেশনাল টেক্সট-টু-স্পিচ এআই বট।\n\n"
        "নিচে থেকে আপনার পছন্দের ভয়েস নির্বাচন করুন এবং যেকোনো বাংলা লেখা পাঠান।", 
        reply_markup=reply_markup
    )

async def button_click(update: Update, context: ContextTypes.DEFAULT_TYPE):
    query = update.callback_query
    await query.answer()
    user_id = query.from_user.id
    selected_voice = query.data
    user_voices[user_id] = VOICES.get(selected_voice, VOICES["male_bd"])

    voice_name = "পুরুষ (Pradeep)" if "Pradeep" in user_voices[user_id] else "নারী (Nabanita)"
    await query.edit_message_text(
        text=f"✅ ভয়েস সেট হয়েছে: **{voice_name}**\nএখন আপনার বাংলা লেখাটি পাঠান।",
        parse_mode="Markdown"
    )

async def convert_text_to_speech(update: Update, context: ContextTypes.DEFAULT_TYPE):
    text = update.message.text
    user_id = update.message.from_user.id
    selected_voice = user_voices.get(user_id, VOICES["male_bd"])

    msg = await update.message.reply_text("🎙️ প্রফেশনাল ভয়েস তৈরি হচ্ছে...")
    output_file = f"voice_{user_id}.mp3"

    try:
        communicate = edge_tts.Communicate(text, selected_voice)
        await communicate.save(output_file)

        with open(output_file, 'rb') as audio:
            await update.message.reply_audio(audio=audio, caption="Generated by Sapan Voice Bot")
    except Exception as e:
        await update.message.reply_text("⚠️ ভয়েস জেনারেট করতে সমস্যা হয়েছে। আবার চেষ্টা করুন।")
    finally:
        await msg.delete()
        if os.path.exists(output_file):
            os.remove(output_file)

def main():
    app = Application.builder().token(BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CallbackQueryHandler(button_click))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, convert_text_to_speech))

    print("Bot is running...")
    app.run_polling()

if __name__ == '__main__':
    main()
